export const RESOURCE_CONSTANTS = {
  VALIDATION: {
    HEX_COLOR_REGEX: /^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$/,
    MIN_TITLE_LENGTH: 1,
    MAX_TITLE_LENGTH: 100,
    MAX_DESCRIPTION_LENGTH: 500,
  },
  ERROR_MESSAGES: {
    INVALID_COLOR_FORMAT: 'Invalid color format. Please provide a valid hex color (e.g., #F1C231).',
    RESOURCE_NOT_FOUND: 'Resource not found',
    AMENITY_NOT_FOUND: 'Amenity not found',
    CLUB_NOT_FOUND: 'Club not found',
    FAILED_TO_CREATE_RESOURCE: 'Failed to create resource',
    FAILED_TO_CREATE_AMENITY: 'Failed to create amenity',
    FAILED_TO_UPDATE_RESOURCE: 'Failed to update resource',
    FAILED_TO_UPDATE_AMENITY: 'Failed to update amenity',
    FAILED_TO_DELETE_RESOURCE: 'Failed to delete resource',
    FAILED_TO_DELETE_AMENITY: 'Failed to delete amenity',
  },
  DEFAULT_VALUES: {
    ENABLE_ONLINE_BOOKING: true,
    STATUS: 'active',
    AMENITY_DEFAULTS: {
      restaurant: false,
      hotel: false,
      drinks: false,
      food: false,
      hotShower: false,
      kidsRoom: false,
      wifi: false,
      bar: false,
      changingRoom: false,
      parking: false,
      lockerRoom: false,
      proShop: false,
      coaching: false,
      physiotherapy: false,
      massage: false,
    },
  },
} as const;
